[package]
name = "address"
version = "0.1.0"
edition = "2021"
description = "CLI for comparing address databases."

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "address"

[dependencies]
aid = { git = "https://github.com/grantspassoregon/aid.git" }
clap = { version = "4.1.1", features = ["derive"] }
csv = "1.3.0"
indicatif = { version = "0.17.3", features = ["rayon"] }
nom = "7.1.3"
rayon = "1.6.1"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.56"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
criterion = "0.4.0"
plotters = "0.3.4"

# [[bench]]
# name = "compare_records"
# harness = false
