[package]
name = "address"
version = "0.1.0"
edition = "2021"
description = "CLI for comparing address databases."

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "address"

[features]
ci = []

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
clap = { version = "4.5.26", features = ["derive"] }
convert_case = "0.7.1"
csv = "1.3.1"
derive-getters = "0.5.0"
derive-new = "0.7.0"
derive_more = { version = "1.0.0", features = ["full"] }
derive_setters = "0.1.6"
galileo = { git = "https://github.com/Maximkaaa/galileo" }
# galileo = { path = "../galileo/galileo" }
galileo-types = { git = "https://github.com/Maximkaaa/galileo" }
indicatif = { version = "0.17.9", features = ["rayon"] }
nom = "7.1.3"
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.11.1", features = ["serde", "v4"] }

[dev-dependencies]
criterion = "0.5.1"
plotters = "0.3.7"
test-log = { version = "0.2.16", features = ["trace"] }

[[bench]]
name = "compare_records"
harness = false

[profile.bench]
debug = true
