[package]
name = "address"
version = "0.1.0"
edition = "2021"
description = "CLI for comparing address databases."

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "address"

[features]
ci = []

[dependencies]
aid = { git = "https://github.com/grantspassoregon/aid.git", default-features = false, features = [
  "bin",
  "parse",
] }
bincode = "1.3.3"
clap = { version = "4.5.17", features = ["derive"] }
csv = "1.3.0"
derive_more = { version = "1.0.0", features = ["full"] }
galileo = { git = "https://github.com/Maximkaaa/galileo" }
# galileo = { path = "../galileo/galileo" }
galileo-types = { git = "https://github.com/Maximkaaa/galileo" }
indicatif = { version = "0.17.8", features = ["rayon"] }
nom = "7.1.3"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[dev-dependencies]
criterion = "0.5.1"
plotters = "0.3.7"

# [[bench]]
# name = "compare_records"
# harness = false
